-- Ispit iz URBP, Januar 2 2024/2025

SELECT UG.INDEKS, UG.SKGODINA, SS.NAZIV,
        COALESCE(SUM(P.ESPB), 0) AS UPISANO_ESPB,
        COALESCE(SUM(
                 CASE
                     WHEN I.INDEKS IS NOT NULL THEN P.ESPB
                     ELSE 0
                 END
                 ), 0) AS POLOZENO_ESPB,
        AVG(
        CASE
            WHEN I.INDEKS IS NOT NULL THEN I.OCENA + 0.0
        END
        ) AS PROSECNA_OCENA
FROM DA.UPISGODINE UG
    JOIN DA.STUDENTSKISTATUS SS ON UG.IDSTATUSA = SS.ID
    LEFT JOIN DA.UPISANKURS UK ON UG.SKGODINA = UK.SKGODINA
                                 AND UG.INDEKS = UK.INDEKS
    LEFT JOIN DA.ISPIT I ON UK.INDEKS = I.INDEKS
                           AND UK.SKGODINA = I.SKGODINA
                           AND UK.IDPREDMETA = I.IDPREDMETA
                           AND I.STATUS = 'o'
                           AND I.OCENA > 5
    LEFT JOIN DA.PREDMET P ON UK.IDPREDMETA = P.ID
GROUP BY UG.INDEKS, UG.SKGODINA, SS.NAZIV;

CREATE TABLE DA.STATISTIKA (
    INDEKS          INTEGER     NOT NULL,
    SKGODINA        SMALLINT    NOT NULL,
    STATUS          VARCHAR(50) NOT NULL,
    UPISANI_ESPB    INTEGER     NOT NULL,
    POLOZENI_ESPB   INTEGER     NOT NULL,
    PROSECNA_OCENA  DOUBLE,
    PRIMARY KEY (INDEKS, SKGODINA),
    FOREIGN KEY FK_UPISGODINE (INDEKS, SKGODINA) REFERENCES DA.UPISGODINE,
    CONSTRAINT  CHK_UPISANI_ESPB    CHECK (UPISANI_ESPB >= 0),
    CONSTRAINT  CHK_POLOZENI_ESPB   CHECK (POLOZENI_ESPB >= 0 AND POLOZENI_ESPB <= UPISANI_ESPB),
    CONSTRAINT  CHK_PROSECNA_OCENA  CHECK (PROSECNA_OCENA IS NULL OR (PROSECNA_OCENA >= 6.0 AND PROSECNA_OCENA <= 10.0))
);

INSERT INTO DA.STATISTIKA
SELECT UG.INDEKS, UG.SKGODINA, SS.NAZIV,
        COALESCE(SUM(P.ESPB), 0) AS UPISANO_ESPB,
        COALESCE(SUM(
                 CASE
                     WHEN I.INDEKS IS NOT NULL THEN P.ESPB
                     ELSE 0
                 END
                 ), 0) AS POLOZENO_ESPB,
        AVG(
        CASE
            WHEN I.INDEKS IS NOT NULL THEN I.OCENA + 0.0
        END
        ) AS PROSECNA_OCENA
FROM DA.UPISGODINE UG
    JOIN DA.STUDENTSKISTATUS SS ON UG.IDSTATUSA = SS.ID
    LEFT JOIN DA.UPISANKURS UK ON UG.SKGODINA = UK.SKGODINA
                                 AND UG.INDEKS = UK.INDEKS
    LEFT JOIN DA.ISPIT I ON UK.INDEKS = I.INDEKS
                           AND UK.SKGODINA = I.SKGODINA
                           AND UK.IDPREDMETA = I.IDPREDMETA
                           AND I.STATUS = 'o'
                           AND I.OCENA > 5
    LEFT JOIN DA.PREDMET P ON UK.IDPREDMETA = P.ID
GROUP BY UG.INDEKS, UG.SKGODINA, SS.NAZIV;

CREATE VIEW DA.STATISTIKA_BUDZET AS
SELECT S.INDEKS, S.SKGODINA, S.UPISANI_ESPB, S.POLOZENI_ESPB, S.PROSECNA_OCENA,
       SP.NAZIV AS PROGRAM,
       CASE
           WHEN POLOZENI_ESPB >= 48 THEN 'Budzet'
           ELSE 'Samofinansiranje'
       END AS OSTVAREN_STATUS
FROM DA.STATISTIKA S
    JOIN DA.DOSIJE D ON (S.INDEKS = D.INDEKS)
    JOIN DA.STUDIJSKIPROGRAM SP ON (D.IDPROGRAMA = SP.ID)
WHERE S.STATUS = 'Budzet';

SELECT SB.PROGRAM, SB.SKGODINA,
       COUNT(
        CASE
            WHEN SB.OSTVAREN_STATUS = 'Budzet' THEN 1
        END
       ) AS ZADRZALI_STATUS,
       AVG(SB.POLOZENI_ESPB+0.0) AS POLOZENI_ESPB
FROM DA.STATISTIKA_BUDZET SB
GROUP BY SB.PROGRAM, SB.SKGODINA;

DROP VIEW DA.STATISTIKA_BUDZET;

DELETE FROM DA.STATISTIKA
WHERE POLOZENI_ESPB = 0;

ALTER TABLE DA.STATISTIKA
ADD CONSTRAINT CHK_UPISANI_ESPB_2 CHECK (UPISANI_ESPB > 0)
ADD CONSTRAINT CHK_POLOZENI_ESPB_2 CHECK (POLOZENI_ESPB > 0)
ALTER COLUMN PROSECNA_OCENA SET NOT NULL;

CALL SYSPROC.ADMIN_CMD('REORG TABLE DA.STATISTIKA')

WITH NEPOLOZENI_KURSEVI AS (
    SELECT UK.INDEKS, UK.SKGODINA, UK.IDPREDMETA
    FROM DA.UPISANKURS UK
    WHERE NOT EXISTS(
        SELECT *
        FROM DA.ISPIT I
        WHERE UK.INDEKS = I.INDEKS
          AND UK.SKGODINA = I.SKGODINA
          AND UK.IDPREDMETA = I.IDPREDMETA
          AND I.STATUS = 'o'
          AND I.OCENA > 5
    )
), KURSEVI_POLOZENO AS (
    SELECT K.IDPREDMETA, K.SKGODINA, COUNT(I.INDEKS) AS BROJ_STUDENATA, AVG(I.OCENA+0.0) AS PROSEK
    FROM DA.KURS K
        LEFT JOIN DA.ISPIT I ON (K.IDPREDMETA = I.IDPREDMETA AND K.SKGODINA = I.SKGODINA)
    GROUP BY K.IDPREDMETA, K.SKGODINA
)
SELECT S.SKGODINA, S.INDEKS, P.NAZIV, KP.BROJ_STUDENATA, KP.PROSEK
FROM DA.STATISTIKA S
    JOIN NEPOLOZENI_KURSEVI NK ON (S.INDEKS = NK.INDEKS AND S.SKGODINA = NK.SKGODINA)
    JOIN DA.PREDMET P ON (NK.IDPREDMETA = P.ID)
    JOIN KURSEVI_POLOZENO KP ON (KP.SKGODINA = NK.SKGODINA AND KP.IDPREDMETA = NK.IDPREDMETA);

DROP TABLE DA.STATISTIKA;

-- Napraviti okidač koji sprečava brisanje predmeta sa brojem espb bodova većim od 15.

CREATE TRIGGER DA.PREDMETI_VISE_OD_15
BEFORE DELETE
ON DA.PREDMET
REFERENCING
    OLD AS O
FOR EACH ROW
WHEN(ESPB > 15)
BEGIN ATOMIC
    SIGNAL SQLSTATE '75000' ('Nije dozvoljeno brisanje predmeta koji nose vise od 15 espb bodova.');
END;

DELETE FROM DA.PREDMET WHERE ESPB > 15;
